name: Build Helm package
description: Build Helm package and push to ECR
inputs:
  version:
    description: Helm version
    required: false
    default: 0.1.0-test
  aws-access-key-id:
    description: AWS access key id for ECR
    required: true
  aws-secret-access-key:
    description: AWS secret access key for ECR
    required: true
  aws-region:
    description: AWS region
    required: true
  ecr-repo-prefix:
    description: Repository prefix
    required: true
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1-node16
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.aws-region }}
  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1
  - name: Build and publish on ECR
    shell: bash
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      ECR_REPOSITORY: ${{ inputs.ecr-repo-prefix }}/${{ github.event.repository.name }}
    run: |
      mkdir ${{ env.REPO_NAME }}
      cp -fr devops/Helm/. ${{ env.REPO_NAME }}/
      helm package -u ${{ env.REPO_NAME }}/ -n ${{ env.ECR_REPOSITORY }} --version ${{ inputs.version }}
      helm push ${{ env.REPO_NAME }}-${{ inputs.version }}.tgz oci://${{ env.ECR_REGISTRY }}/${{ inputs.ecr-repo-prefix }}
