name: Push the Docker image to ECR and scan the image
description: Push the Docker image to ECR and scan the image
inputs:
  image:
    description: Full name of the Docker image
    required: true
  image-tag:
    description: Docker image tag
    required: true
  ecr-repository: 
    description: ECR repository that the image is stored
    required: true
  aws-access-key-id:
    description: 'AWS key for ECR access'
    required: true
  aws-secret-access-key:
    description: 'AWS secret for ECR access'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: push Docker image to ECR
      shell: bash
      run: docker push ${{ inputs.IMAGE }}
    - name: Scan Docker image
      uses: alexjurkiewicz/ecr-scan-image@v1.7.0
      with:
        repository: ${{ inputs.ecr-repository }}
        tag: ${{ inputs.image-tag }}
        fail_threshold: high
