name: Deploy on EKS cluster
description: Deploy on EKS cluster
inputs:
  aws-access-key-id:
    description: AWS access key id. This access key is should have read ECR permission and read/write EKS permission
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
  ecr-repo-prefix:
    description: Repository prefix
    required: true
  image-tag:
    description: tag of the container image
    required: true
  helm-version:
    description: version of the helm chart
    required: true
  eks-cluster:
    description: ARN of the EKS cluster
    required: true
  eks-namespace:
    description: namespace to deploy
    required: true
  value-replacements:
    description: override values in values.yaml
    required: false
runs:
  using: composite
  steps:
      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull helm chart
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repo-prefix }}/${{ github.event.repository.name }}
        run: |
          helm pull oci://${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }} --version ${{ inputs.helm-version }} --untar
      - name: Helm deployment
        uses: bitovi/github-actions-deploy-eks-helm@v1.1.0
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
          cluster-name: ${{ inputs.eks-cluster }}
          chart-path: ${{ github.event.repository.name }}/
          namespace: ${{ inputs.eks-namespace }}
          values: ${{ inputs.value-replacements }}
          name: ${{ github.event.repository.name }} 
          helm-wait: true
          atomic: true

