name: Create/Update targets of an AWS EventBridge rule
description: Create/Update targets of an AWS EventBridge rule

inputs:
  aws-access-key-id:
    description: 'AWS key for EventBridge access'
    required: true
  aws-secret-access-key:
    description: 'AWS secret for EventBridge access'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  rule-name:
    description: EventBridge rule name
    required: true
  event-bus:
    description: Event bus name
    required: false
  targets:
    description: Targets of the EventBridge rule
    required: true

runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1-node16
    with:
      aws-access-key-id: ${{ inputs.aws-access-key-id }}
      aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
      aws-region: ${{ inputs.aws-region }}
  - uses: jannekem/run-python-script-action@v1
    id: script
    with:
      fail-on-error: false
      script: |
        import boto3
        try: 
          client = boto3.client('events')
          response = client.put_targets(
            Rule='${{ inputs.rule-name' }}',
            EventBusName='${{ inputs.event-bus }}',
            Targets=${{ inputs.targets }})