name: Determine deployment envirionment from Github action context

on:
  workflow_call:
    outputs:
      environment:
        description: deployment environment
        value: ${{ jobs.get-env.outputs.environment }}
jobs:
  get-env:
    name: Determine deployment envirionment from Github action context
    runs-on: self-hosted
    outputs:
      environment: ${{ steps.env.outputs.ENVIRONMENT }}
      runner: ${{ steps.env.outputs.RUNNER }}
    steps:
      - name: Determine deployment environment
        id: env
        shell: bash
        run: |
          if [ '${{ github.event_name }}' == 'release' ]
          then 
            echo "ENVIRONMENT=prod" >> $GITHUB_OUTPUT
          elif [ '${{ github.event_name }}' == 'push' ] && [ '${{ github.ref_name }}' == 'main' ]
          then
            echo "ENVIRONMENT=stage" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_OUTPUT
          fi
          echo "RUNNER=self-hosted" >> $GITHUB_OUTPUT
      - shell: bash
        run: |
          echo "Deployment environment: ${{ steps.env.outputs.ENVIRONMENT }}"
          echo "Github action: ${{ steps.env.outputs.RUNNER }}"
